name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Check code style
        run: poetry run black --check --line-length 120 audio_transformers tests
      - name: Lint the code
        run: poetry run flake8 audio_transformers tests --count --max-complexity=10 --max-line-length=120 --statistics
      - name: Run Tests
        run: poetry run pytest
      - name: Coveralls
        uses: coverallsapp/github-action@v2
